### ISSUE TITLE
EPIC: Basic dogs managment

### ISSUE THREAD

**Issue by Annibor** [Annibor/dog-adoption#3]
Develop the core functionality of the dog list, that will show different dogs available for adoption form the adoption centre. 

**Front-End Tasks:**

- [ ] **Dogs Components:** Design and implement components for displaying dogs, show only one dog.
- [ ] ** MOre components** Design adn implement components for users to add dog to save list.

**Back-End Tasks:**

- [ ] **Dog Model: **Create a model for dogs that includes fields like name, breed, bio, good wiht chidlren ect.
- [ ] ** Dog Model** Add function for filtering and search fucntion.
