### ISSUE TITLE
EPIC: Pages

### ISSUE THREAD

**Issue by Annibor** [Annibor/dog-adoption#37]
As a developer I want a good layout for the pages so that visitors and users esaily can navigate on the page, and understand what thay need to do. 

Acceptance criterias:
- [ ] Create home page structure with components ect.
- [ ] Create dogs page with components ect.
- [ ] Create profile page with components ect.
- [ ] Create logion page with components ect.
- [ ] Create register page with components ect.
